kind: pipeline
name: terraform-kubernetes-astronomer

steps:

- name: lint
  image: hashicorp/terraform:light
  commands:
    - cp providers.tf.example providers.tf
    - terraform init
    - terraform fmt -check=true
    - terraform validate -var "deployment_id=validate" -var "db_connection_string=fake" -var "tls_cert=fake" -var "tls_key=fake" -var "base_domain=fake.com"
    - |
      for example in $(find examples -maxdepth 1 -mindepth 1 -type d); do
      cp providers.tf $example
      cd $example
      echo $example
      terraform init
      terraform fmt -check=true
      terraform validate -var "deployment_id=citest"
      cd -
      done
    - terraform -v
  when:
    event:
      - pull_request
      - push

- name: terraform_apply
  image: sjmiller609/helm-kubectl-terraform:latest
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  commands:
    - EXAMPLE=aws pipeline/run_terraform.sh
  when:
    event:
      - push
    branch:
      - master

- name: terraform_destroy
  image: sjmiller609/helm-kubectl-terraform:latest
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  commands:
    - DESTROY=1 EXAMPLE=aws pipeline/run_terraform.sh
  when:
    event:
      - push
    status:
      - failure
      - success
    branch:
      - master
